# Generated by Django 4.2.5 on 2023-09-05 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DummyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pick_up_day",
                    models.CharField(
                        choices=[("środa", "Środa"), ("czwartek", "Czwartek")],
                        max_length=10,
                    ),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Producer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("order", models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_type",
                    models.CharField(
                        choices=[
                            ("is_running_out", "Is Running Out"),
                            ("to_order", "To Order"),
                            ("is_new", "Is New"),
                            ("is_discounted", "Is Discounted"),
                            ("is_weighted", "Is Weighted"),
                        ],
                        max_length=50,
                    ),
                ),
                ("desc", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="WeightScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        choices=[
                            (0.01, "0,01"),
                            (0.02, "0,02"),
                            (0.03, "0,03"),
                            (0.04, "0,04"),
                            (0.05, "0,05"),
                            (0.1, "0,1"),
                            (0.2, "0,2"),
                            (0.3, "0,3"),
                            (0.4, "0,4"),
                            (0.5, "0,5"),
                            (0.6, "0,6"),
                            (0.7, "0,7"),
                            (0.8, "0,8"),
                            (0.9, "0,9"),
                            (1, "1"),
                            (1.5, "1,5"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                            (20, "20"),
                            (30, "30"),
                            (40, "40"),
                            (50, "50"),
                        ],
                        decimal_places=3,
                        max_digits=7,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("in_storage", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "max_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "quantity_in_stock",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "quantity_ordered_this_week",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "quantity_to_order",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("order_deadline", models.DateField()),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="form.producer"
                    ),
                ),
                (
                    "statuses",
                    models.ManyToManyField(related_name="products", to="form.status"),
                ),
                (
                    "weight_scheme",
                    models.ManyToManyField(
                        related_name="products", to="form.weightscheme"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("item_ordered", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="form.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="form.product"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(through="form.OrderItem", to="form.product"),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
