# Generated by Django 4.2.5 on 2023-09-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weightscheme",
            name="quantity",
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
