# Generated by Django 4.2.5 on 2023-09-07 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0002_alter_weightscheme_quantity"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DummyModel",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="item_ordered",
            new_name="item_ordered_date",
        ),
    ]
