# Generated by Django 4.2.5 on 2023-09-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0003_delete_dummymodel_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="max_quantity",
            new_name="quantity_max",
        ),
        migrations.RemoveField(
            model_name="product",
            name="in_storage",
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="order_deadline",
            field=models.DateField(null=True),
        ),
    ]
