# Generated by Django 4.2.5 on 2023-09-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0004_rename_max_quantity_product_quantity_max_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="quantity_max",
            new_name="order_max_quantity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="quantity_ordered_this_week",
        ),
        migrations.RemoveField(
            model_name="product",
            name="quantity_to_order",
        ),
        migrations.AddField(
            model_name="order",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="is_given",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity_delivered_this_week",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="orders", through="form.OrderItem", to="form.product"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="order_deadline",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity_in_stock",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="status",
            name="status_type",
            field=models.CharField(max_length=50),
        ),
    ]
