# Generated by Django 4.2.5 on 2023-09-13 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0005_rename_quantity_max_product_order_max_quantity_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="weight_scheme",
            new_name="weight_schemes",
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderitems",
                to="form.order",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="producer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="form.producer",
            ),
        ),
    ]
