# Generated by Django 4.2.5 on 2023-09-13 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0006_rename_weight_scheme_product_weight_schemes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="orders",
                through="form.OrderItem",
                to="form.product",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderitems",
                to="form.product",
            ),
        ),
    ]
