# Generated by Django 4.2.5 on 2023-09-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0009_alter_order_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-order_date"]},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ["-item_ordered_date"]},
        ),
        migrations.AlterModelOptions(
            name="producer",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="status",
            options={"ordering": ["status_type"]},
        ),
        migrations.AlterModelOptions(
            name="weightscheme",
            options={"ordering": ["quantity"]},
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name="producer",
            name="description",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="producer",
            name="name",
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name="producer",
            name="order",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="order_max_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity_in_stock",
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name="status",
            name="status_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="weightscheme",
            name="quantity",
            field=models.DecimalField(decimal_places=3, max_digits=6, unique=True),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["order", "product"], name="form_orderi_order_i_08ef3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="form_produc_name_e24d85_idx"),
        ),
    ]
