# Generated by Django 4.2.5 on 2023-09-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0010_alter_order_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-date_created"]},
        ),
        migrations.RenameField(
            model_name="order",
            old_name="order_date",
            new_name="date_created",
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["date_created"], name="form_order_date_cr_d28678_idx"
            ),
        ),
    ]
