# Generated by Django 4.2.5 on 2023-09-18 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0011_alter_order_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_archived",
        ),
    ]
