# Generated by Django 4.2.5 on 2023-09-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0013_producer_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producer",
            name="slug",
            field=models.CharField(unique=True),
        ),
    ]
