# Generated by Django 4.2.5 on 2023-09-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0014_alter_producer_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producer",
            name="slug",
            field=models.CharField(blank=True, unique=True),
        ),
    ]
