# Generated by Django 4.2.5 on 2023-09-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0016_alter_product_order_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="statuses",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="form.status"
            ),
        ),
    ]
