# Generated by Django 4.2.5 on 2023-09-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0017_alter_product_statuses"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ["item_ordered_date"]},
        ),
        migrations.AlterField(
            model_name="product",
            name="order_max_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=10000, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity_delivered_this_week",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity_in_stock",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=9, null=True
            ),
        ),
    ]
