# Generated by Django 4.2.5 on 2023-10-05 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0018_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
    ]
