# Generated by Django 4.2.5 on 2023-10-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0019_remove_order_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
