# Generated by Django 4.2.6 on 2023-10-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0020_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="order_max_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=9999, max_digits=9
            ),
        ),
    ]
