# Generated by Django 4.2.6 on 2023-10-26 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0021_alter_product_order_max_quantity"),
    ]

    state_operations = [
        migrations.CreateModel(
            name="product_weight_schemes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productweightschemes",
                        to="form.product",
                    ),
                ),
                (
                    "weightscheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productweightschemes",
                        to="form.weightscheme",
                    ),
                ),
            ],
        ),
        migrations.AlterModelTable(
            name="product_weight_schemes",
            table="form_product_weight_schemes",
        ),
        migrations.AlterField(
            model_name="product",
            name="weight_schemes",
            field=models.ManyToManyField(
                related_name="products",
                through="form.product_weight_schemes",
                to="form.weightscheme",
            ),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.AlterModelTable(
            name="product_weight_schemes",
            table="form_product_weight_schemes",
        ),
    ]
