# Generated by Django 4.2.7 on 2023-11-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0023_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="pick_up_day",
            field=models.CharField(
                choices=[("wednesday", "Środa"), ("thursday", "Czwartek")],
                max_length=10,
            ),
        ),
    ]
