# Generated by Django 4.2.7 on 2023-11-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0024_alter_order_pick_up_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="pick_up_day",
            field=models.CharField(
                choices=[("środa", "środa"), ("czwartek", "czwartek")], max_length=10
            ),
        ),
    ]
