# Generated by Django 4.2.7 on 2023-11-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0026_producer_not_arrived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity_delivered_this_week",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=-1, max_digits=9, null=True
            ),
        ),
    ]
