# Generated by Django 4.2.7 on 2023-11-19 17:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0027_alter_product_quantity_delivered_this_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.DecimalField(
                choices=[
                    (Decimal("0.000"), "0"),
                    (Decimal("0.500"), "0.5"),
                    (Decimal("1.000"), "1"),
                    (Decimal("2.000"), "2"),
                    (Decimal("3.000"), "3"),
                    (Decimal("4.000"), "4"),
                    (Decimal("5.000"), "5"),
                ],
                decimal_places=3,
                max_digits=6,
            ),
        ),
    ]
