# Generated by Django 4.2.7 on 2023-12-07 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("form", "0030_producer_short_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplies",
                        to="form.producer",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["producer__short", "name"]},
        ),
        migrations.CreateModel(
            name="SupplyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=6)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplyitems",
                        to="form.product",
                    ),
                ),
                (
                    "supply",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplyitems",
                        to="form.supply",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="supply",
            name="product",
            field=models.ManyToManyField(
                blank=True,
                related_name="supplies",
                through="form.SupplyItem",
                to="form.product",
            ),
        ),
        migrations.AddField(
            model_name="supply",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
