# Generated by Django 4.2.7 on 2023-12-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0031_supply_alter_product_options_supplyitem_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supply",
            options={"ordering": ["producer__short", "-date_created"]},
        ),
        migrations.AlterModelOptions(
            name="supplyitem",
            options={"ordering": ["supply", "-date_created"]},
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="form_produc_name_e24d85_idx",
        ),
        migrations.AlterField(
            model_name="product",
            name="order_max_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=9, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="supply",
            index=models.Index(
                fields=["date_created"], name="form_supply_date_cr_8d4d8b_idx"
            ),
        ),
    ]
