# Generated by Django 4.2.7 on 2023-12-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0032_alter_supply_options_alter_supplyitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="jedzenie"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="info",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[("S", "S"), ("W", "W"), ("G", "G")], default="S"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
