# Generated by Django 4.2.7 on 2024-02-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0035_remove_supplyitem_product_remove_supplyitem_supply_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producer",
            name="order_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity_delivered_this_week",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=9, null=True
            ),
        ),
    ]
