# Generated by Django 4.2.7 on 2024-03-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0036_producer_order_deadline_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producer",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="product",
            name="is_stocked",
            field=models.BooleanField(default=False),
        ),
    ]
