# Generated by Django 4.2.7 on 2024-03-13 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0038_category_remove_product_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="new_category",
            new_name="category",
        ),
    ]
