# Generated by Django 4.2.11 on 2024-06-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0042_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producer",
            name="manager_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="producer",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="producer",
            name="short",
            field=models.CharField(default="test", max_length=16),
        ),
        migrations.AlterField(
            model_name="producer",
            name="slug",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="subcategory",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[("S", "S"), ("W", "W"), ("G", "G")], max_length=100
            ),
        ),
    ]
