# Generated by Django 4.2.11 on 2024-04-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0042_alter_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=0,
                max_digits=6,
                verbose_name="kwota zamówienia",
            ),
        ),
    ]
