# Generated by Django 4.2.11 on 2024-04-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0043_order_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="difference",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=7,
                verbose_name="różnica",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="paid",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=7,
                verbose_name="zapłacono",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=7,
                verbose_name="kwota zamówienia",
            ),
        ),
    ]
