# Generated by Django 4.2.11 on 2024-04-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0044_order_difference_order_paid_alter_order_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount_with_fund",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=7,
                verbose_name="kwota po funduszu",
            ),
        ),
    ]
