# Generated by Django 4.2.11 on 2025-09-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0044_order_paid_amount_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="fund_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                verbose_name="Fundusz w momencie rozliczenia zamówienia.",
            ),
        ),
    ]
