# Generated by Django 4.2.11 on 2024-04-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0045_order_amount_with_fund"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cash",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=7,
                verbose_name="gotówka",
            ),
        ),
    ]
