# Generated by Django 4.2.11 on 2024-04-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0046_order_cash"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="credit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=6,
                verbose_name="nadpłata/dług",
            ),
        ),
    ]
