# Generated by Django 4.2.11 on 2025-08-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reports_start_day",
                    models.DateTimeField(
                        blank=True,
                        help_text="Użyj tego pola, aby zmienić początkową datę i godzinę 7-dniowego przedziału dla którego generowane są raporty. Domyślna data i godzina rozpoczęcia przedziału to ostatnia sobota o 1 w nocy. Chcąc sprawdzić raport dla archiwalnego tygodnia należy wybrać sobotę, od której zacznie się raport, oraz godzinę 1:00 w nocy i zapisać. Po sprawdzeniu archiwalnego tygodnia należy wykasować wartość tego pola i zapisać, aby przywrócić funkcjonowanie raportów!!!",
                        null=True,
                        verbose_name="Początkowa data raportów",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konfiguracja Aplikacji",
            },
        ),
    ]
