# Generated by Django 4.2.11 on 2025-08-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appconfig",
            options={
                "verbose_name": "Konfiguracja Aplikacji",
                "verbose_name_plural": "Konfiguracja Aplikacji",
            },
        ),
        migrations.AddField(
            model_name="appconfig",
            name="homepage_info",
            field=models.CharField(
                blank=True,
                default="",
                max_length=2500,
                verbose_name="Info na stronie głównej",
            ),
        ),
    ]
