# Generated by Django 4.2.11 on 2025-08-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_appconfig_options_appconfig_homepage_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appconfig",
            name="homepage_info",
            field=models.TextField(
                blank=True, default="", verbose_name="Info na stronie głównej"
            ),
        ),
    ]
