name: koop_form
version: 1.0.0 #docker compose version
services:
  webapp:
    image: koop_form:0.1.0a7
    environment:
      ENV_CONFIG_PATH: /env
      ALLOWED_HOSTS_CONFIG_PATH: /allowhosts

    configs:
      - env
      - allowhosts
    volumes:
      - static-volume:/app/koop_form/staticfiles
    networks:
      - back-tier

  nginx:
    image: openresty/openresty:1.25.3.1-2-alpine-fat

  #  command: ["nginx", "-c" ,"/nginx-conf/main-nginx.conf"]
    ports:
      - "80:80"  # Expose port 80 of the container to port 80 on the host
      - "443:443"
      - "9145:9145"

    volumes:
      - ./main-nginx.conf:/etc/nginx/conf.d/default.conf  # Mount your Nginx configuration file
      - ./nginx-conf:/nginx-conf
      - static-volume:/app/koop_form/staticfiles
      - ./website.crt:/website.crt
      - ./website.key:/website.key
      - ./nginx-lua-prometheus:/nginx-lua-prometheus
    depends_on:
      - webapp  # Ensure webapp service starts before Nginx
    networks:
      - back-tier

  database:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
    configs:
      - source: init_empty_config
        target: /docker-entrypoint-initdb.d/empty.sql
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - back-tier

volumes:
  db-data: {}
  static-volume: {}

configs:
  init_empty_config:
    file: ./init_empty_config
  env:
    file: ./.myenv_example
  allowhosts:
    file: ./allowhosts.json

networks:
  # The presence of these objects is sufficient to define them
  back-tier: {}
