# Generated by Django 4.2.7 on 2023-11-09 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="budget",
            new_name="fund",
        ),
    ]
