# Generated by Django 4.2.7 on 2023-11-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_userprofile_fund"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="koop_id",
            field=models.PositiveIntegerField(default=5, unique=True),
            preserve_default=False,
        ),
    ]
