# Generated by Django 4.2.11 on 2025-05-17 15:22
from decimal import Decimal

from django.db import migrations, models


def create_user_profile_fund(apps, schema_editor):
    UserProfileFund = apps.get_model("user", "UserProfileFund")
    UserProfileFund(value=Decimal("1.1")).save()
    UserProfileFund(value=Decimal("1.3")).save()


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_userprofile_koop_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfileFund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="Wartość funduszu.", unique=True
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_user_profile_fund, migrations.RunPython.noop),
        migrations.RenameField(
            model_name="userprofile",
            old_name="fund",
            new_name="_fund",
        ),
    ]
