# Generated by Django 4.2.11 on 2024-04-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_userprofile_koop_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="credit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=6,
                verbose_name="nadpłata/dług",
            ),
        ),
    ]
