# Generated by Django 4.2.11 on 2025-05-17 15:36
from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion



def assign_fund_to_user_profile(apps, schema_editor):
    UserProfileFund = apps.get_model("user", "UserProfileFund")
    fund_1_1 = UserProfileFund.objects.get(value=Decimal("1.1"))
    fund_1_3 = UserProfileFund.objects.get(value=Decimal("1.3"))
    UserProfile = apps.get_model("user", "UserProfile")
    for profile in UserProfile.objects.all():
        if profile._fund == Decimal("1.1"):
            profile.fund = fund_1_1
        elif profile._fund == Decimal("1.3"):
            profile.fund = fund_1_3
        else:
            profile.fund = fund_1_3
        profile.save(update_fields=["fund"])


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_userprofilefund"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="fund",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="user.userprofilefund",
                verbose_name="Fundusz",
            ),
        ),
        migrations.RunPython(assign_fund_to_user_profile, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="userprofile",
            name="fund",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="user.userprofilefund",
                verbose_name="Fundusz",
            ),
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="_fund",
        )
    ]
