# Generated by Django 4.2.11 on 2025-05-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_userprofile_fund"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="allow_emails",
            field=models.BooleanField(default=False),
        ),
    ]
