# Generated by Django 4.2.11 on 2025-05-20 20:10

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0007_userprofile_allow_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="payment_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=7,
                verbose_name="Dług / nadpłata",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="allow_emails",
            field=models.BooleanField(
                default=False, verbose_name="Zgoda na maile systemowe"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="koop_id",
            field=models.PositiveIntegerField(unique=True, verbose_name="Koop ID"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Numer telefonu"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Użytkownik",
            ),
        ),
    ]
