# Generated by Django 4.2.11 on 2024-03-27 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("form", "0041_alter_category_options_alter_order_options_and_more"),
        ("supply", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supply",
            options={
                "ordering": ["producer__short", "-date_created"],
                "verbose_name": "Dostawa",
                "verbose_name_plural": "Dostawy",
            },
        ),
        migrations.AlterModelOptions(
            name="supplyitem",
            options={
                "ordering": ["supply", "-date_created"],
                "verbose_name": "Produkt w dostawie",
                "verbose_name_plural": "Produkty w dostawie",
            },
        ),
        migrations.AlterField(
            model_name="supply",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="utworzono"),
        ),
        migrations.AlterField(
            model_name="supply",
            name="producer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplies",
                to="form.producer",
                verbose_name="producent",
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="product",
            field=models.ManyToManyField(
                blank=True,
                related_name="supplies",
                through="supply.SupplyItem",
                to="form.product",
                verbose_name="produkt",
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="użytkownik",
            ),
        ),
        migrations.AlterField(
            model_name="supplyitem",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="utworzono"),
        ),
        migrations.AlterField(
            model_name="supplyitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplyitems",
                to="form.product",
                verbose_name="produkt",
            ),
        ),
        migrations.AlterField(
            model_name="supplyitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3, max_digits=6, verbose_name="ilość"
            ),
        ),
        migrations.AlterField(
            model_name="supplyitem",
            name="supply",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplyitems",
                to="supply.supply",
                verbose_name="dostawa",
            ),
        ),
    ]
