# TODO: cleanups and further simplifications
# TODO: rework volumes to have persistency on the disk and easier backups? How does the backups work on the IONOS server?

services:
  webapp:
    build:
      context: ../
    # TODO: we are getting rid of env_file block in favour of inlined envs.
    #       if we will ever need a compose for local testing env we can always create a local override file instead of a whole dir structure.
    env_file:
      - path: ./configs/koop_form/additional_envs # TODO: where can I find this file? Anything important there? Should I login int the live container and extract it?
        required: false
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev # TODO: do we need to define new production config for the new server/DNS name? 
      ENV_CONFIG_PATH: /env
      ALLOWED_HOSTS_CONFIG_PATH: /allowhosts
    configs:
      - env
      - allowhosts
    ports:
      - 8000:8000 # TODO: remove this after initial testsing
    volumes:
      - static-volume:/app/koop_form/staticfiles

  # TODO: recreate this using Caddy - should be much simpler, with the cert auto-renewed from Lets Encrypt
  # TODO: ask Marcin about the prometheus metrics - why do we need them? We could probably get rid of it and have a simpler setup?

  # nginx:
  #   image: openresty/openresty:1.25.3.1-2-alpine-fat
  #   ports:
  #     - "80:80"  # Expose port 80 of the container to port 80 on the host
  #     - "443:443"
  #     - "9145:9145"
  #   volumes:
  #     - ./main-nginx.conf:/etc/nginx/conf.d/default.conf  # Mount your Nginx configuration file
  #     - ./nginx-lua-prometheus:/nginx-lua-prometheus
  #     - ../parameters/nginx-conf:/nginx-conf
  #     - static-volume:/app/koop_form/staticfiles
  #     - ../parameters/website.crt:/website.crt
  #     - ../parameters/website.key:/website.key
  #   depends_on:
  #     - webapp  # Ensure webapp service starts before Nginx

  database:
    # TODO: use a more recent postgres version? 
    #       Also - maybe reuse a postgres instance from other apps? 
    #       Running several instances may be a little too heavy on the server.
    #       But running a single DB has its own issues, we would probably need to create a separate lifecycle management for it.
    #       Or even switch to sqlite?
    image: postgres:14 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password # TODO: update the user+password for production
      POSTGRES_DB: koop_db
    volumes:
      - db-data:/var/lib/postgresql/data
      # This is how we can automate initial migration the old DB into new setup.
      # It will be ignored if we already have anything.
      # We can also reuse it as subsequent emergency restore from future backups.
      # Although its probably safer to avoid automated restoration - can be a source of serious user confusion.
      - ./data/db_backup_dump.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432 # TODO: remove this after initial testsing

volumes:
  db-data: {}
  static-volume: {}

configs:
  env:  # TODO: where can I find this file? Anything important there? Should I login int the live container and extract it?
    file: ./configs/koop_form/koop-envs
  allowhosts: 
    file: ./configs/koop_form/allowhosts.json
