from django.urls import path

from apps.report.views import (
    ProducerSuppliesReportView,
    ProducerBoxReportView,
    UsersReportView,
    ProducerBoxListView,
    ProducersFinanceReportView,
    ProducerBoxReportDownloadView,
    UsersReportDownloadView,
    ProducersFinanceReportDownloadView,
    ProducerSuppliesReportDownloadView,
    OrderBoxListView,
    OrderBoxReportView,
    OrderBoxReportDownloadView,
    UsersFinanceReportView,
    ProducerSuppliesListView,
    MassProducerBoxReportDownloadView,
    UsersFinanceReportDownloadView,
    MassOrderBoxReportDownloadView, ProducerOrdersReportView, ProducerOrdersReportDownloadView,
    ProducerOrdersListView, ProductsExcessReportView,
)


urlpatterns = [
    path(
        "producenci-dostawy/",
        ProducerSuppliesListView.as_view(),
        name="producer-supplies-list",
    ),
    path(
        "producenci-zamowienia/",
        ProducerOrdersListView.as_view(),
        name="producer-orders-list",
    ),
    path(
        "producenci-dostawy/<str:slug>/",
        ProducerSuppliesReportView.as_view(),
        name="producer-supplies-report",
    ),
    path(
        "producenci-zamowienia/<str:slug>/",
        ProducerOrdersReportView.as_view(),
        name="producer-orders-report",
    ),
    path(
        "producenci-skrzynki/",
        ProducerBoxListView.as_view(),
        name="producer-box-list",
    ),
    path(
        "producenci-skrzynki/<str:slug>/",
        ProducerBoxReportView.as_view(),
        name="producer-box-report",
    ),
    path(
        "kooperanci/",
        UsersReportView.as_view(),
        name="users-report",
    ),
    path(
        "producenci-finanse/",
        ProducersFinanceReportView.as_view(),
        name="producers-finance",
    ),
    path(
        "pobierz/producenci-skrzynki/<str:slug>/",
        ProducerBoxReportDownloadView.as_view(),
        name="producer-box-report-download",
    ),
    path(
        "pobierz/kooperanci/",
        UsersReportDownloadView.as_view(),
        name="users-report-download",
    ),
    path(
        "pobierz/producenci-finanse/",
        ProducersFinanceReportDownloadView.as_view(),
        name="producers-finance-report-download",
    ),
    path(
        "pobierz/producenci-dostawy/<str:slug>/",
        ProducerSuppliesReportDownloadView.as_view(),
        name="producer-supplies-report-download",
    ),
    path(
        "pobierz/producenci-zamowienia/<str:slug>/",
        ProducerOrdersReportDownloadView.as_view(),
        name="producer-orders-report-download",
    ),
    path(
        "zamowienia-skrzynki/",
        OrderBoxListView.as_view(),
        name="order-box-list",
    ),
    path(
        "zamowienia-skrzynki/<int:pk>/",
        OrderBoxReportView.as_view(),
        name="order-box-report",
    ),
    path(
        "pobierz/zamowienia-skrzynki/<int:pk>/",
        OrderBoxReportDownloadView.as_view(),
        name="order-box-report-download",
    ),
    path(
        "kooperanci-finanse/",
        UsersFinanceReportView.as_view(),
        name="users-finance-report",
    ),
    path(
        "pobierz/wszyscy-producenci-skrzynki/",
        MassProducerBoxReportDownloadView.as_view(),
        name="mass-producer-box-report-download",
    ),
    path(
        "pobierz/kooperanci-finanse/",
        UsersFinanceReportDownloadView.as_view(),
        name="users-finance-report-download",
    ),
    path(
        "pobierz/wszystkie-zamowienia-skrzynki/",
        MassOrderBoxReportDownloadView.as_view(),
        name="mass-order-box-report-download",
    ),
    path(
        "nadwyzki/",
        ProductsExcessReportView.as_view(),
        name="excess-report",
    ),
]
